### ISSUE TITLE
Drogowy system ostrzegawczy

### ISSUE THREAD

**Issue by szymonleyk** [greedo85/KursJava#58]
Napisz program który:
- umożliwia przekazanie do systemu informacji o zdarzeniu
- mamy do dyspozycji następujące zdarzenia: wypadek, kontrola prędkości
- system przechowuje informacje o zdarzeniach
- jeśli kilka osób próbuje przekazać informację o tym samym zdarzeniu, to system zapisuje tylko pierwsze
- zdarzenie posiada: długość geograficzną, szerokość geograficzną oraz typ zdarzenia (wypadek, kontrola prędkości)
- zdarzenie jest takie samo gdy wszystkie jego dane są takie same
- możliwość wyświetlenia wszystkich aktualnych zdarzeń
- z konsoli powinien być dostęp do odpowiednich metod (dodawania/wyświetlania zdarzeń)
- po dodaniu zdarzenia, system powinien poinformować "zdarzenie już jest w naszym systemie, dziękujemy" lub "jesteś pierwszą osobą, która informuje nas o tym zdarzeniu, dziękujemy"
- w przypadku braku zdarzeń powinien pojawić się komunikat "brak zdarzeń na drodze"

**Comment by greedo85** [comment]
Zadanie rozwiązane
