### ISSUE TITLE
Testy wydajnościowe dla wybranych kolekcji

### ISSUE THREAD

**Issue by szymonleyk** [greedo85/KursJava#60]
Napisz bibliotekę, która:
- wygeneruj X imion i X nazwisk
- oblicz czas operacji dodawania, pobierania, wyszukiwani i usuwania, dla ArrayList, LinkedList, HashSet, LinkedHashSet, TreeSet

wyniki dla:
X = 1000
X = 10000
X = 1000000

**Comment by greedo85** [comment]
Cześć, przypomnisz mi o której jutro?

**Comment by szymonleyk** [comment]
13
--
Szymon Leyk
737 871 638 niedziela, 08 listopada 2020, 04:32PM +01:00 od greedo85  notifications@github.com :
